### PR TITLE
🧹 Allowed mocking the function for retrieving the container image from a remote registry

### LINKED ISSUE #198: Allow stubbing/mocking out the image/tag fetching for test cases
When running test cases locally, the codepaths will perform the full image/tag-to-SHA256 resolution.

Our test cases shouldn't fail just because DockerHub is down. Modify the way the image resolution is called so that it can be stubbed/mocked out for test cases.

This will keep us from unnecessarily making registry API calls (and eating through any limited quota there), and will allow development of mondoo-operator from a disconnected network environment.

### PR DESCRIPTION
**Pull request by imilchev**
Fixes #198

### CODE REVIEW

File: controllers/suite_test.go [hunk 1]
```diff
@@ -55,6 +60,19 @@ func TestAPIs(t *testing.T) {
 var _ = BeforeSuite(func() {
 	logf.SetLogger(zap.New(zap.WriteTo(GinkgoWriter), zap.UseDevMode(true)))
 
+	// Mock the retrieval of the actual image from the remote registry
+	getRemoteImage = func(ref name.Reference, options ...remote.Option) (*remote.Descriptor, error) {
```
Comment (joelddiaz) [inline controllers/suite_test.go:64]: Seems so awkward to mock this out for these Gingko-style tests... But it does seem to work.

This kind of mock would also be needed for the non-Gingko-style tests in controlers/webhooks_test.go

Comment (imilchev) [reply controllers/suite_test.go:64]: I will add the mock in the webhook tests as well. Just for traceability I will add what we discussed here.

We concluded that on the long term it will be best if we use the same testing style across all Mondoo projects. Therefore when we expanding the unit tests for the controller, we will gradually move away from Ginko-style tests.

**Review by joelddiaz — COMMENTED** [review]
👍 LGTM
