### PR TITLE
🐛 Fix `MondooAuditConfig` Status Reconcile

### LINKED ISSUE #433: Re-write mondooauditconfig Reconcile in a re-entrant way
**Describe the bug**
The current implementation might create race-conditions when not run single-threaded.

See comment here: https://github.com/mondoohq/mondoo-operator/pull/395#discussion_r913832053

**To Reproduce**
-

**Expected behavior**
Reconcile should only do one thing and then re-iterate.

**Screenshots**
-

**Additional context**
Perhaps also defer the status update, as done here:
https://github.com/mondoohq/mondoo-operator/pull/408/files#diff-95f7e0c1611028f1d111b1f9ebada14e1b8919e068ccb23fbd3cd37b19d7b797R181

### PR DESCRIPTION
**Pull request by czunker**
This should prevent any race-conditions, which were previously possible.

Fixes #433

Signed-off-by: Christian Zunker <christian@mondoo.com>

### CODE REVIEW

**Comment by imilchev** [comment]
What does this fix exactly?

**Comment by czunker** [comment]
> What does this fix exactly?

@joelddiaz suspected some race conditions here: https://github.com/mondoohq/mondoo-operator/pull/395#discussion_r913832053

Part of the fix was already done with https://github.com/mondoohq/mondoo-operator/pull/408. But that introduced an update to 
`ReconciledByOperatorVersion`, which could indicate success when not everything was reconciled.

So, basically, with #395, I updated and saved the `MondooAuditConfig` not in an operator-like manner.

File: controllers/mondooauditconfig_controller_test.go [hunk 1]
```diff
@@ -384,9 +383,12 @@ func TestMondooAuditConfigStatus(t *testing.T) {
 	})
 	assert.NoError(t, err)
 
-	assert.NotEmptyf(t, reconciler.MondooAuditConfig.Status, "Status shouldn't be empty")
-	assert.NotEmptyf(t, reconciler.MondooAuditConfig.Status.ReconciledByOperatorVersion, "ReconciledByOperatorVersion shouldn't be empty")
-	assert.Equalf(t, reconciler.MondooAuditConfig.Status.ReconciledByOperatorVersion, version.Version, "expected versions to be equal")
+	err = fakeClient.Get(context.TODO(), client.ObjectKeyFromObject(mondooAuditConfig), mondooAuditConfig)
+	assert.NoError(t, err)
```
Comment (joelddiaz) [inline controllers/mondooauditconfig_controller_test.go:387]: s/assert/require/ since the asserts() that follow reach into the mondooAuditConfig which is the same mondooAuditConfig as in line 365 (so I could see us getting some weird assertion errors that are about what testMondooAuditConfig() returned instead of the results of the Get()

**Comment by imilchev** [comment]
> > What does this fix exactly?
> 
> @joelddiaz suspected some race conditions here: [#395 (comment)](https://github.com/mondoohq/mondoo-operator/pull/395#discussion_r913832053)
> 
> Part of the fix was already done with #408. But that introduced an update to `ReconciledByOperatorVersion`, which could indicate success when not everything was reconciled.
> 
> So, basically, with #395, I updated and saved the `MondooAuditConfig` not in an operator-like manner.

but it seems like this is only a problem if we have multi-threaded operator, which we don't AFAIK. That's why I was wondering why this is a problem

**Comment by joelddiaz** [comment]
> but it seems like this is only a problem if we have multi-threaded operator, which we don't AFAIK. That's why I was wondering why this is a problem

Yeah, I don't see anywhere where we change the MaxConcurrentReconciles on the controller, so we're effectively single-threaded even in the case of two MondooAuditConfig resources.

But I would consider it concerning to store temporary/ephemeral things into the shared instantiation of `MondooAuditConfigReconciler` (assuming it really is a single instance of it that the manager sets up).

File: controllers/mondooauditconfig_controller_test.go (hunk 1 above)
Comment (czunker) [reply controllers/mondooauditconfig_controller_test.go]: Thanks. Hopefully, I'll remember this from now on. It's not the first time you find this in my changes.
